# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-30 02:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='end_time',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='start_time',
            field=models.IntegerField(),
        ),
    ]
